### ISSUE TITLE
Docs publishing failed due to incorrect Markdown link

### ISSUE THREAD

**Issue by ringods** [ctfer-io/pulumi-ctfd#48]
@pandatix The first publishing run failed:

https://github.com/pulumi/registry/actions/runs/8527241375/job/23358235302?pr=4251#step:8:25

When looking at the related Markdown file, I think the forward slash in this link should be removed:

https://github.com/ctfer-io/pulumi-ctfd/blob/fc5725fd35b0e323814cd7f65fba4aef9533a495/docs/installation-configuration.md#L34

**Comment by pandatix** [comment]
I'm providing a fix ASAP.

In the meantime, is there a recommendation for Markdown linting in Pulumi(verse) to detect those errors sooner (i.e. in this repo workflows) ?

**Comment by pandatix** [comment]
@ringods fixed through v0.1.22 :)

**Comment by pandatix** [comment]
Produced once again with v0.1.22 due to other MD issues.
Added markdownlint on push/PRs to ensure we won't see that soon :)

**Comment by pandatix** [comment]
`v0.1.23` should contain the fixes once for all !

**Comment by pandatix** [comment]
Doc was published successfully 🎉
